const slideOrderIds = new Set(["@id-pptx-slide-permutation","@id-pptx-slide-permutation-refusal"]);
const textBoxIds = new Set(["@id-pptx-text-box-authoring","@id-pptx-text-box-refusal"]);
const pptxTableIds = new Set(["@id-pptx-table-roundtrip-geometry","@id-pptx-table-formatting","@id-pptx-table-stale-handle","@id-pptx-table-atomic-refusals"]);
const pptxNoopId = new Set(['@id-pptx-bun-open-save-noop']);
const threadIds = new Set(["@id-docx-existing-thread-inspection","@id-docx-existing-thread-resolution","@id-docx-existing-thread-noop","@id-docx-existing-thread-refusal","@id-docx-existing-thread-rollback","@id-docx-existing-thread-encoding","@id-docx-existing-thread-unsupported","@id-docx-existing-thread-limit"]);
const commentIds = new Set(["@id-docx-comments-inspection","@id-docx-comments-resolution","@id-docx-comments-noop","@id-docx-comments-refusal"]);
const relationshipIds = new Set(["@id-office-relationship-prefix-alias","@id-office-relationship-wrong-uri"]);
const custodyIds = new Set(["@id-bun-opc-open-refusal","@id-bun-opc-detached-byte-copies","@id-bun-opc-preserve-utf16le-edit","@id-bun-opc-async-transaction-refusal","@id-bun-opc-thenable-transaction-result","@id-bun-opc-save-invalid-target-custody","@id-bun-opc-symlink-destination-refusal"]);
const coreOpcIds = new Set(["@id-opc-package-corpus-noop","@id-opc-package-transaction-rollback","@id-opc-package-preserve-unrelated"]);
const budgetId = new Set(['@id-package-admission-negative-budget']);
const descriptorId = new Set(['@id-zip-unsigned-descriptor-signature-collision']);
const boundId = new Set(['@id-zip-bounds']);
const unsafeId = new Set(['@id-zip-refuse-unsafe']);
const positiveIds = new Set(["@id-zip-read-valid","@id-zip-write-deterministic"]);
import {test,expect} from 'bun:test';
import {execFileSync} from 'node:child_process';
import {cases} from '../scripts/verify.ts';

const id='@id-docx-go-body-insert-order',path='workflows/docx/paragraphs.feature';
const steps=['a new Word body with no elements','First and Third paragraphs are appended, then Second is inserted at index one','element counts after each operation are one, two and three','paragraph texts in order equal First, Second and Third'];
test('Bun and Go execute exact empty-body insertion counts and order without Python or saved credit',async()=>{
 const ledger=await Bun.file('ledgers/workflows.json').json();
 const prior=JSON.parse(execFileSync('git',['show','779415af623f7d7536a8bce5d4b3b7204193d653:ledgers/workflows.json']).toString());
 const current=ledger.workflows.find((w:any)=>w.id===id),old=prior.workflows.find((w:any)=>w.id===id);
 expect(current.feature).toBe(path);expect(current.expandedCases).toBe(1);
 expect(cases(path,await Bun.file(path).text()).filter((r:any)=>r.scenarioId===id).map((r:any)=>r.steps.map((s:any)=>s.text))).toEqual([steps]);
 expect(current.expectedOutcomes).toEqual(steps.slice(2));
 expect(old.consumers.bun.status).toBe('planned');expect(current.consumers.bun.status).toBe('implemented');
 for(const marker of ['e6a05f508a447da6d23ff5cc3681a7bccd879332','shared v0.70.0','tests/acceptance/body-insertion.ts','tests/unit/docx-insert-paragraph.test.ts','732/732','Fresh GitHub recursive make check','In-memory'])expect(current.consumers.bun.evidence).toContain(marker);
 expect(old.consumers.go.status).toBe('planned');expect(current.consumers.go.status).toBe('implemented');
 for(const marker of ['7f0a6b2e620ece9f1a962c78969dcf7b26ee77c5','shared v0.70.0','acceptance/body_insert_order_test.go','349 selected cases/1193 steps/0 failures/0 skips','reports/batches/198.md','Fresh post-push GitHub recursive test-batch','In-memory'])expect(current.consumers.go.evidence).toContain(marker);
 expect(current.consumers.python).toEqual(old.consumers.python);
 const laterIds=new Set(["@id-docx-format-preserve","@id-docx-xml-space","@id-docx-table-paragraph","@id-docx-stale-span","@id-docx-refuse-topology","@id-docx-create-minimal-package","@id-docx-create-style-validation","@id-docx-create-stale-opaque","@id-docx-create-atomic-refusals","@id-docx-table-create-roundtrip","@id-docx-table-opaque-preserve","@id-docx-table-stale-cell","@id-docx-table-atomic-refusals","@id-docx-direct-font-size-half-points","@id-xml-parse-offsets","@id-xml-normalise-line-endings","@id-xml-parse-refusals","@id-xml-parse-bounds","@id-xml-apply-edits","@id-xml-entity-values","@id-xml-stylesheet-processing-instruction","@id-xml-expanded-attribute-lookup","@id-xml-implicit-xml-prefix","@id-xml-prototype-safe-attributes","@id-xml-immutable-namespace-metadata","@id-xml-escaping-values","@id-xml-escaping-invalid-character","@id-xml-escaping-whitespace-roundtrip","@id-xml-typed-parse-error","@id-xml-invalid-qname-components","@id-xml-unicode-qname-components","@id-xml-outside-root-nbsp","@id-xml-comparison-prefix-and-opc-order","@id-xml-comparison-significant-content","@id-xml-comparison-prefix-attribute-binding","@id-xml-comparison-unsafe-input","@id-xml-comparison-processing-instructions-and-comments","@id-package-admission-unsafe-members","@id-package-admission-resource-limits","@id-package-admission-unsupported-compression","@id-package-admission-unsafe-xml-members","@id-package-diff-equivalent-xml-and-binary-changes","@id-zip-crc32-standard-vector","@id-bun-zip32-reader-refusal","@id-bun-zip32-writer-refusal","@id-bun-zip32-configured-bounds","@id-xml-parse-offsets","@id-xml-normalise-line-endings","@id-xml-parse-refusals","@id-xml-parse-bounds"]);
 const unchanged=structuredClone(current);unchanged.consumers.bun=old.consumers.bun;unchanged.consumers.go=old.consumers.go;expect(unchanged).toEqual(old);
 expect(ledger.workflows.filter((w:any)=>!slideOrderIds.has(w.id)&&!textBoxIds.has(w.id)&&!pptxTableIds.has(w.id)&&!pptxNoopId.has(w.id)&&!threadIds.has(w.id)&&!commentIds.has(w.id)&&!relationshipIds.has(w.id)&&!custodyIds.has(w.id)&&!coreOpcIds.has(w.id)&&!budgetId.has(w.id)&&!descriptorId.has(w.id)&&!boundId.has(w.id)&&!unsafeId.has(w.id)&&!positiveIds.has(w.id)&&w.id!==id&&!laterIds.has(w.id))).toEqual(prior.workflows.filter((w:any)=>!slideOrderIds.has(w.id)&&!textBoxIds.has(w.id)&&!pptxTableIds.has(w.id)&&!pptxNoopId.has(w.id)&&!threadIds.has(w.id)&&!commentIds.has(w.id)&&!relationshipIds.has(w.id)&&!custodyIds.has(w.id)&&!coreOpcIds.has(w.id)&&!budgetId.has(w.id)&&!descriptorId.has(w.id)&&!boundId.has(w.id)&&!unsafeId.has(w.id)&&!positiveIds.has(w.id)&&w.id!==id&&!laterIds.has(w.id)));
});
