const pythonPackageIds = new Set(['@id-package-admission-negative-budget','@id-zip-unsigned-descriptor-signature-collision']);
const goXmlNegativeIds = new Set(['@id-xml-comparison-significant-content','@id-xml-comparison-prefix-attribute-binding','@id-xml-comparison-unsafe-input','@id-xml-comparison-processing-instructions-and-comments']);
const goLatentPackageIds = new Set(['@id-package-admission-negative-budget','@id-zip-unsigned-descriptor-signature-collision']);
const pythonXmlNegativeIds = new Set(['@id-xml-comparison-significant-content','@id-xml-comparison-prefix-attribute-binding','@id-xml-comparison-unsafe-input','@id-xml-comparison-processing-instructions-and-comments']);
const pythonPhysicalOverlapId = '@id-zip-physical-member-overlap-refusal';
const goRemainingFormulaIds = new Set(['@id-xlsx-go-formula-literal-punctuation','@id-xlsx-go-static-remap-exact','@id-xlsx-go-static-remap-refusal','@id-xlsx-go-static-reference-properties']);
const pythonCommentVmlId = '@id-xlsx-comment-vml-existing-graph';
const styleAuthoringIds = new Set(['@id-docx-paragraph-style-authoring','@id-docx-paragraph-style-authoring-refusal']);
const goFormulaAnalysisIds = new Set(['@id-xlsx-go-formula-analysis-counts','@id-xlsx-go-formula-quoted-sheet-flags','@id-xlsx-go-formula-analysis-refusal']);
const pageLayoutIds = new Set(['@id-docx-final-section-layout','@id-docx-final-section-layout-refusal']);
const effectiveIds = new Set(['@id-docx-effective-run-formatting','@id-docx-effective-run-formatting-refusal']);
const trackingIds = new Set(['persistence','custody','no-op','refusal','rollback','plain-edit','author-refusal'].map(name => '@id-docx-tracking-settings-'+name));
const goDirectRangeIds = new Set(['@id-xlsx-go-direct-range-parsing','@id-xlsx-go-direct-range-refusal']);
const formulaIds = new Set(["@id-xlsx-go-formula-analysis-counts","@id-xlsx-go-formula-quoted-sheet-flags","@id-xlsx-go-formula-analysis-refusal","@id-xlsx-go-formula-literal-punctuation","@id-xlsx-go-direct-range-parsing","@id-xlsx-go-direct-range-refusal","@id-xlsx-go-static-remap-exact","@id-xlsx-go-static-remap-refusal","@id-xlsx-go-static-reference-properties"]);
const commentVmlId = '@id-xlsx-comment-vml-existing-graph';
const cellStyleIds = new Set(["@id-xlsx-cell-style-selection","@id-xlsx-cell-style-refusal"]);
const xlsxCreateIds = new Set(["@id-xlsx-create-native-default","@id-xlsx-create-add-worksheet","@id-xlsx-create-prefixed-missing-cell","@id-xlsx-create-coordinate-boundary","@id-xlsx-create-row-ordering","@id-xlsx-create-invalid-params-atomic","@id-xlsx-create-existing-fixture-append"]);
const slideOrderIds = new Set(["@id-pptx-slide-permutation","@id-pptx-slide-permutation-refusal"]);
const textBoxIds = new Set(["@id-pptx-text-box-authoring","@id-pptx-text-box-refusal"]);
const pptxTableIds = new Set(["@id-pptx-table-roundtrip-geometry","@id-pptx-table-formatting","@id-pptx-table-stale-handle","@id-pptx-table-atomic-refusals"]);
const pptxNoopId = new Set(['@id-pptx-bun-open-save-noop']);
const threadIds = new Set(["@id-docx-existing-thread-inspection","@id-docx-existing-thread-resolution","@id-docx-existing-thread-noop","@id-docx-existing-thread-refusal","@id-docx-existing-thread-rollback","@id-docx-existing-thread-encoding","@id-docx-existing-thread-unsupported","@id-docx-existing-thread-limit"]);
const commentIds = new Set(["@id-docx-comments-inspection","@id-docx-comments-resolution","@id-docx-comments-noop","@id-docx-comments-refusal"]);
const relationshipIds = new Set(["@id-office-relationship-prefix-alias","@id-office-relationship-wrong-uri"]);
const custodyIds = new Set(["@id-bun-opc-open-refusal","@id-bun-opc-detached-byte-copies","@id-bun-opc-preserve-utf16le-edit","@id-bun-opc-async-transaction-refusal","@id-bun-opc-thenable-transaction-result","@id-bun-opc-save-invalid-target-custody","@id-bun-opc-symlink-destination-refusal"]);
const coreOpcIds = new Set(["@id-opc-package-corpus-noop","@id-opc-package-transaction-rollback","@id-opc-package-preserve-unrelated"]);
const budgetId = new Set(['@id-package-admission-negative-budget']);
const descriptorId = new Set(['@id-zip-unsigned-descriptor-signature-collision']);
const boundId = new Set(['@id-zip-bounds']);
const unsafeId = new Set(['@id-zip-refuse-unsafe']);
import {test,expect} from 'bun:test';
import {execFileSync} from 'node:child_process';
import {cases} from '../scripts/verify.ts';

const path='workflows/xlsx/calculation-chain-lifecycle.feature';
const id='@id-xlsx-owned-calculation-chain-invalidation';
test('the owned-chain case has one bounded identity; Bun default refusal is separate from opt-in success',async()=>{
 const text=await Bun.file(path).text(),rows=cases(path,text);
 expect(rows).toHaveLength(1);expect(rows[0]?.scenarioId).toBe(id);
 const registry=await Bun.file('ledgers/workflows.json').json(),entry=registry.workflows.find((w:any)=>w.id===id);
 expect(registry.features.filter((p:string)=>p===path)).toHaveLength(1);
 expect(entry?.feature).toBe(path);expect(entry?.expandedCases).toBe(1);
 expect(entry?.consumers.bun.status).toBe('implemented');
 for(const evidence of ['c9892d2c891f54ec0802b1d0cdf88b645ece5637','14 exact shared steps','730/730 selected cases','1,112 native tests','v0.56'])expect(entry?.consumers.bun.evidence).toContain(evidence);
 const refusal=await Bun.file('ledgers/consumers/bun-xlsx-owned-chain-refusal.json').json();
 expect(refusal.source.revision).toBe('19af500df68c3f345fc661675925b995337fd9f4');
 expect(refusal.mappings).toHaveLength(2);
 expect(refusal.mappings.every((m:any)=>m.coverage==='unmapped'&&m.scenarioIds.length===0&&m.executionCredit===false)).toBe(true);
 expect(refusal.mappings.map((m:any)=>m.sourceSha256)).toEqual(Array(2).fill('03c539d05cd48d8187c028c16bcecf901fede3ab80d025853a456ea2d2449249'));
 expect(entry?.consumers.go.status).toBe('implemented');
 expect(entry?.consumers.python.status).toBe('implemented');
 for(const evidence of ['7fdc10f5371e7842f13713e81462bb657789128f','1 case/14 passed steps','19-case/159-step','1,324 tests','shared v0.48 82a67a1'])expect(entry?.consumers.python.evidence).toContain(evidence);
 for(const evidence of ['a8515940db69c42294493161fb77b80936f23357','@CHAIN-001','294 selected cases/1004 passed steps/0 failures','reports/batches/160.md','ef75c15eda31503954d28633bccce99364d4442c2a98255e15c5d18a9e432edd'])expect(entry?.consumers.go.evidence).toContain(evidence);
 const previous=JSON.parse(execFileSync('git',['show','3f0fbe2d11f8db6deda69779d5833086ee510799:ledgers/workflows.json']).toString());
 const oldEntry=previous.workflows.find((w:any)=>w.id===id);
 expect(oldEntry.consumers.go.status).toBe('planned');
 const unchanged=structuredClone(entry);unchanged.consumers.go=oldEntry.consumers.go;unchanged.consumers.python=oldEntry.consumers.python;unchanged.consumers.bun=oldEntry.consumers.bun;
 expect(unchanged).toEqual(oldEntry);
 const visibility='workflows/pptx/slide-visibility.feature';
 expect(registry.features.filter((p:string)=>p!==visibility)).toEqual(previous.features);
 const exceptions=new Set([id,'@id-xlsx-cross-sheet-cache-invalidation','@id-zip-physical-member-overlap-refusal','@id-office-xlsx-independent-style-reader','@id-docx-go-run-effects-getters','@id-docx-go-run-underline-style','@id-docx-go-run-font-name','@id-docx-go-run-color-getter','@id-docx-go-run-highlight','@id-docx-go-run-vertical-align','@id-docx-go-roundtrip-selected-formatting','@id-docx-go-table-merge-properties','@id-docx-go-table-style-getter','@id-docx-go-table-header-getter','@id-docx-go-cell-shading-getter','@id-docx-go-cell-properties-getters','@id-docx-go-table-dimensions-getters','@id-docx-go-table-cell-access','@id-docx-go-table-cell-text-getters','@id-docx-go-table-row-counts','@id-docx-go-new-empty-body','@id-docx-go-roundtrip-table-text','@id-docx-go-core-properties-getters','@id-docx-go-section-title-background-getters','@id-docx-go-paragraph-text-getter', '@id-docx-go-paragraph-alignment-getter', '@id-docx-go-paragraph-spacing-getters', '@id-docx-go-paragraph-advanced-toggles', '@id-docx-go-paragraph-multiple-runs', '@id-docx-go-body-insert-order', '@id-docx-format-preserve', '@id-docx-xml-space', '@id-docx-table-paragraph', '@id-docx-stale-span', '@id-docx-refuse-topology', '@id-docx-create-minimal-package', '@id-docx-create-style-validation', '@id-docx-create-stale-opaque', '@id-docx-create-atomic-refusals', '@id-docx-table-create-roundtrip', '@id-docx-table-opaque-preserve', '@id-docx-table-stale-cell', '@id-docx-table-atomic-refusals', '@id-docx-direct-font-size-half-points','@id-xml-parse-offsets','@id-xml-normalise-line-endings','@id-xml-parse-refusals','@id-xml-parse-bounds','@id-xml-apply-edits', '@id-xml-entity-values', '@id-xml-stylesheet-processing-instruction', '@id-xml-expanded-attribute-lookup', '@id-xml-implicit-xml-prefix', '@id-xml-prototype-safe-attributes', '@id-xml-immutable-namespace-metadata', '@id-xml-escaping-values', '@id-xml-escaping-invalid-character', '@id-xml-escaping-whitespace-roundtrip', '@id-xml-typed-parse-error', '@id-xml-invalid-qname-components', '@id-xml-unicode-qname-components', '@id-xml-outside-root-nbsp', '@id-xml-comparison-prefix-and-opc-order', '@id-xml-comparison-significant-content', '@id-xml-comparison-prefix-attribute-binding', '@id-xml-comparison-unsafe-input', '@id-xml-comparison-processing-instructions-and-comments', '@id-package-admission-unsafe-members', '@id-package-admission-resource-limits', '@id-package-admission-unsupported-compression', '@id-package-admission-unsafe-xml-members', '@id-package-diff-equivalent-xml-and-binary-changes', '@id-zip-crc32-standard-vector', '@id-bun-zip32-reader-refusal', '@id-bun-zip32-writer-refusal', '@id-bun-zip32-configured-bounds','@id-zip-read-valid','@id-zip-write-deterministic']);
 expect(registry.workflows.filter((w:any)=>w.id!=="@id-xml-go-attribute-splice-custody"&&w.id!=="@id-opc-package-preserve-unrelated"&&w.id!=="@id-xml-go-immutable-leaf-seed"&&!pythonPackageIds.has(w.id)&&!goXmlNegativeIds.has(w.id)&&!goLatentPackageIds.has(w.id)&&!pythonXmlNegativeIds.has(w.id)&&w.id!==pythonPhysicalOverlapId&&!goRemainingFormulaIds.has(w.id)&&w.id!==pythonCommentVmlId&&!styleAuthoringIds.has(w.id)&&!goFormulaAnalysisIds.has(w.id)&&!pageLayoutIds.has(w.id)&&!effectiveIds.has(w.id)&&!trackingIds.has(w.id)&&!goDirectRangeIds.has(w.id)&&!formulaIds.has(w.id)&&w.id!==commentVmlId&&!cellStyleIds.has(w.id)&&!xlsxCreateIds.has(w.id)&&!slideOrderIds.has(w.id)&&!textBoxIds.has(w.id)&&!pptxTableIds.has(w.id)&&!pptxNoopId.has(w.id)&&!threadIds.has(w.id)&&!commentIds.has(w.id)&&!relationshipIds.has(w.id)&&!custodyIds.has(w.id)&&!coreOpcIds.has(w.id)&&!budgetId.has(w.id)&&!descriptorId.has(w.id)&&!boundId.has(w.id)&&!unsafeId.has(w.id)&&!exceptions.has(w.id)&&w.feature!==visibility)).toEqual(previous.workflows.filter((w:any)=>w.id!=="@id-xml-go-attribute-splice-custody"&&w.id!=="@id-opc-package-preserve-unrelated"&&w.id!=="@id-xml-go-immutable-leaf-seed"&&!pythonPackageIds.has(w.id)&&!goXmlNegativeIds.has(w.id)&&!goLatentPackageIds.has(w.id)&&!pythonXmlNegativeIds.has(w.id)&&w.id!==pythonPhysicalOverlapId&&!goRemainingFormulaIds.has(w.id)&&w.id!==pythonCommentVmlId&&!styleAuthoringIds.has(w.id)&&!goFormulaAnalysisIds.has(w.id)&&!pageLayoutIds.has(w.id)&&!effectiveIds.has(w.id)&&!trackingIds.has(w.id)&&!goDirectRangeIds.has(w.id)&&!formulaIds.has(w.id)&&w.id!==commentVmlId&&!cellStyleIds.has(w.id)&&!xlsxCreateIds.has(w.id)&&!slideOrderIds.has(w.id)&&!textBoxIds.has(w.id)&&!pptxTableIds.has(w.id)&&!pptxNoopId.has(w.id)&&!threadIds.has(w.id)&&!commentIds.has(w.id)&&!relationshipIds.has(w.id)&&!custodyIds.has(w.id)&&!coreOpcIds.has(w.id)&&!budgetId.has(w.id)&&!descriptorId.has(w.id)&&!boundId.has(w.id)&&!unsafeId.has(w.id)&&!exceptions.has(w.id)));
 const predicates=rows[0]!.steps.map(s=>s.text).join('\n');
 for(const required of ['xl/chains/order.xml','Input!A1','Calc!A1','Calc!B1','Calc!C1','absent or empty cached values','source package bytes remain unchanged','content-type override are absent','destination relationship and content-type target resolves','byte-identical'])expect(predicates).toContain(required);
 const old=await Bun.file('staging/go/features/implemented/spreadsheet/calc-chain.feature').text();
 expect(old).toContain('@CHAIN-001');
 const source=await Bun.file('ledgers/feature-source-consolidation.json').json();
 const staged=source.candidates.find((c:any)=>c.path==='staging/go/features/implemented/spreadsheet/calc-chain.feature');
 expect(staged?.compiledCases).toBe(7);expect(staged?.executionCredit).toBe(false);
});
