import {test,expect} from 'bun:test';
import {Parser,AstBuilder,GherkinClassicTokenMatcher,compile} from '@cucumber/gherkin';
import {IdGenerator} from '@cucumber/messages';
const file='ledgers/functional-equivalence.json';
const candidates=async()=>new Map((await Bun.file('ledgers/feature-source-consolidation.json').json()).candidates.map((c:any)=>[c.path,c]));
async function selected(path:string,id:string){const gen=IdGenerator.incrementing(),doc=new Parser(new AstBuilder(gen),new GherkinClassicTokenMatcher()).parse(await Bun.file(path).text());return compile(doc,path,gen).filter(p=>p.tags.some(t=>t.name===id)).map(p=>({steps:p.steps.map(s=>s.text),name:p.name}));}
test('four reviewed Python duplicate candidates retain provenance and distinguish exact predicate from weak overlap and disjoint variants',async()=>{const r=await Bun.file(file).json(),known=await candidates(),m=await Bun.file('manifest.json').json(),asset=m.files.find((f:any)=>f.path===file);expect(asset.role).toBe('catalogue-reconciliation');expect(asset.sha256).toBe(new Bun.CryptoHasher('sha256').update(await Bun.file(file).bytes()).digest('hex'));expect(r.schemaVersion).toBe(1);expect(r.sourceCommit).toBe('7b7a2fa2610c421cdde9d7b1da9125c8f98b9dd8');expect(r.groups).toHaveLength(4);expect(r.groups.map((g:any)=>g.status)).toEqual(['weak-predicate-only','distinct-parameter-variants','weak-predicate-only','exact-captured-predicate-alias']);expect(r.executionCredit).toBe(false);expect(r.retiredCandidateIds).toEqual([]);const used=new Set<string>();for(const g of r.groups){expect(g.members).toHaveLength(2);expect(g.provenanceRetained).toBe(true);expect(g.reason.length).toBeGreaterThan(25);for(const m of g.members){expect(known.has(m.path)).toBe(true);expect(used.has(m.id)).toBe(false);used.add(m.id);const pickles=await selected(m.path,m.id);expect(pickles).toHaveLength(1);expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(pickles[0]!.steps)).digest('hex')).toBe(g.capturedStepSha256);}}
 const [notes,layout,audit,classes]=r.groups;expect(notes.preconditionsEqual).toBe(false);expect(layout.parameterGroups).toEqual([['title','bullets','table'],['comparison','blank']]);expect(audit.preconditionsEqual).toBe(false);expect(classes.preconditionsEqual).toBe(true);expect(classes.representative).toBe(classes.members[0].id);expect(classes.aliases).toEqual([classes.members[1].id]);});
test('exact predicate alias is only nonempty TOOL_CLASSES, not tool membership or case execution',async()=>{const r=await Bun.file(file).json(),g=r.groups[3],a=await selected(g.members[0].path,g.members[0].id),b=await selected(g.members[1].path,g.members[1].id);expect(a[0]!.steps).toEqual(b[0]!.steps);expect(a[0]!.steps).toEqual(['Import TOOL_CLASSES from tools.','Evaluate len(TOOL_CLASSES).','len(TOOL_CLASSES) is greater than or equal to 1.']);expect(g.observedPredicate).toBe('len(TOOL_CLASSES)>=1');expect(g.executionCredit).toBe(false);});
