import {test,expect} from 'bun:test';
import {execFileSync} from 'node:child_process';
import {cases} from '../scripts/verify.ts';
import {beforePackageAlignmentFeature,beforePackageAlignmentCase,beforePackageAlignmentLedger} from './xml-generalization-helpers.ts';
const hash=(s:string)=>new Bun.CryptoHasher('sha256').update(s).digest('hex');
const load=()=>Bun.file('ledgers/package-alignment.json').json();
test('second twenty-ID package alignment preserves all identities/cases and exact historical evidence outside thirteen changed contracts',async()=>{
 const m=await load();expect(m.selectedIds).toHaveLength(20);expect(new Set(m.selectedIds).size).toBe(20);expect(m.expandedCases).toBe(27);expect(m.compiledSteps).toBe(127);expect(m.executionCredit).toBe(false);expect(m.retiredScenarioIds).toEqual([]);expect(m.files.flatMap((f:any)=>f.scenarios)).toHaveLength(13);
 for(const f of m.files){expect(f.beforeText).toBe(execFileSync('git',['show',m.sourceRevision+':'+f.path],{encoding:'utf8'}));expect(hash(f.beforeText)).toBe(f.beforeSha256);const t=await Bun.file(f.path).text();expect(hash(t)).toBe(f.afterSha256);expect(beforePackageAlignmentFeature(f.path,t)).toBe(f.beforeText);const now=cases(f.path,t),old=cases(f.path,f.beforeText);expect(now.map(beforePackageAlignmentCase)).toEqual(old);for(const s of f.scenarios){expect(now.filter(c=>c.scenarioId===s.id)).toEqual(s.after);expect(s.before).toHaveLength(s.after.length);}}
 const current=await Bun.file('ledgers/workflows.json').json(),old=JSON.parse(execFileSync('git',['show',m.sourceRevision+':ledgers/workflows.json'],{encoding:'utf8'}));expect(beforePackageAlignmentLedger(current)).toEqual(old);for(const r of m.files.flatMap((f:any)=>f.afterLedgerRows))for(const c of ['bun','go','python'])expect(r.consumers[c].status).toBe('planned');
 let count=0,steps=0;for(const p of current.features){const rows=cases(p,await Bun.file(p).text()).filter(c=>m.selectedIds.includes(c.scenarioId));count+=rows.length;steps+=rows.reduce((n,c)=>n+c.steps.length,0);}expect(count).toBe(27);expect(steps).toBe(127);
});
test('concrete ZIP read order, mixed deterministic writer and five independent bounds remain discriminating',async()=>{
 const rows=cases('workflows/package/zip32.feature',await Bun.file('workflows/package/zip32.feature').text()),read=rows.find(c=>c.scenarioId==='@id-zip-read-valid')!,unsafe=rows.find(c=>c.scenarioId==='@id-zip-refuse-unsafe')!,bounds=rows.find(c=>c.scenarioId==='@id-zip-bounds')!,writer=rows.find(c=>c.scenarioId==='@id-zip-write-deterministic')!;
 const table=read.steps[0].argument!.dataTable!.rows.slice(1).map(r=>r.cells.map(c=>c.value));expect(table.map(r=>r[0])).toEqual(['z.bin','dir/','a.xml','m.bin']);expect(table.map(r=>r[1])).toEqual(['STORED','STORED','DEFLATED','STORED']);expect(table.map(r=>JSON.parse(r[2]).length)).toEqual([6,0,4,6]);expect(read.steps[3].text).toContain('["z.bin","a.xml","m.bin"]');expect(unsafe.steps[0].text).toContain('eleven strict ZIP32');expect(unsafe.steps.at(-1)!.text).toContain('zip-end-record-missing');expect(bounds.steps[1].text).toContain('eight FF bytes');expect(bounds.steps[3].text).toContain('before member output');expect(writer.steps[3].text).toContain('at least one of each method');expect(writer.steps.at(-1)!.text).toContain('no archive and unchanged caller members');
});
test('valid comparator operands include exact relationship Types; graph and namespace recipes are fixture-sealed',async()=>{
 const m=await load(),manifest=await Bun.file('manifest.json').json();const comparison=cases('workflows/xml/comparison.feature',await Bun.file('workflows/xml/comparison.feature').text()).find(c=>c.scenarioId==='@id-xml-comparison-prefix-and-opc-order')!;for(const s of comparison.steps.slice(0,2)){expect(s.text).toContain('Type="urn:test/a"');expect(s.text).toContain('Type="urn:test/b"');}expect(comparison.steps.at(-1)!.text).toBe('the comparison result is true');
 const graph=cases('workflows/package/graph.feature',await Bun.file('workflows/package/graph.feature').text());expect(graph).toHaveLength(4);const diff=graph.find(c=>c.scenarioId==='@id-opc-diff-content-type')!;expect(diff.steps[2].text).toContain('["[Content_Types].xml","word/document.xml"]');expect(diff.steps[3].text).toContain('identical payload bytes');
 for(const f of m.files)for(const s of f.scenarios)for(const c of s.after)for(const step of c.steps)for(const id of step.text.match(/fixture-[a-f0-9]{64}/g)??[])expect(manifest.files.some((a:any)=>a.id===id&&a.role==='fixture')).toBe(true);
 const relationships=cases('workflows/package/relationship-namespaces.feature',await Bun.file('workflows/package/relationship-namespaces.feature').text());expect(relationships).toHaveLength(4);expect(relationships.filter(c=>c.scenarioId==='@id-office-relationship-prefix-alias').every(c=>c.steps[1].text.includes('production')&&c.steps[2].text.includes('exact value'))).toBe(true);
});
test('unknown predicate changes and invented runtime credit cannot be hidden by historical migration',async()=>{
 const m=await load(),f=m.files[0],text=await Bun.file(f.path).text();expect(()=>beforePackageAlignmentFeature(f.path,text.replace('at least one of each method','only STORED'))).toThrow('Unreviewed');const current=await Bun.file('ledgers/workflows.json').json();current.workflows.find((r:any)=>r.id===f.scenarios[0].id).consumers.go.status='implemented';expect(()=>beforePackageAlignmentLedger(current)).toThrow('Unreviewed');
});
