import {test,expect} from 'bun:test';
import {inflateRawSync} from 'node:zlib';
import {cases} from '../scripts/verify.ts';
import {registerWorkflow,registerAsset} from '../scripts/register-workflow.ts';
import {inspectFixtureArchive} from '../scripts/fixture-content.ts';
import {beforeOutlinesLedger} from './outlines-history.ts';
import {beforeOpacityLedger} from './opacity-history.ts';
import {beforeGradientsLedger} from './gradients-history.ts';
import {beforeZOrderLedger} from './z-order-history.ts';
import {beforeFreeformLedger} from './freeform-history.ts';
import {beforeAutoShapesLedger} from './autoshapes-history.ts';
import {beforeSmartArtCopyLedger} from './smartart-copy-history.ts';
import {beforeSmartArtInspectionLedger} from './smartart-inspection-history.ts';
import {beforeDiagramsLedger} from './diagrams-history.ts';
import {beforeConnectorsLedger} from './connectors-history.ts';
import {beforeGroupTransformLedger} from './group-transform-history.ts';
import {beforeShapeGroupLedger} from './shape-group-history.ts';
import {beforePictureDeleteLedger} from './picture-delete-history.ts';
import {beforePictureSvgLedger} from './picture-svg-history.ts';
import {beforePictureTransformLedger} from './picture-transform-history.ts';
import {beforePictureCropLedger} from './picture-crop-history.ts';
import {beforePicturePlacementLedger} from './picture-placement-history.ts';
import {beforePictureReplacementLedger} from './picture-replacement-history.ts';
import {beforePictureInsertionLedger} from './picture-insertion-history.ts';
import {beforePictureInspectionLedger,beforePictureInspectionFeature} from './picture-inspection-history.ts';
const load=()=>Bun.file('ledgers/pptx-picture-inspection.json').json();
function payloads(bytes:Uint8Array):Map<string,Uint8Array>{
 inspectFixtureArchive(bytes);
 const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let end=bytes.length-22;
 while(v.getUint32(end,true)!==0x06054b50)end--;
 const parts=new Map<string,Uint8Array>();let p=v.getUint32(end+16,true);
 for(let i=0;i<v.getUint16(end+10,true);i++){
  const method=v.getUint16(p+10,true),length=v.getUint16(p+28,true),extra=v.getUint16(p+30,true),comment=v.getUint16(p+32,true),local=v.getUint32(p+42,true),size=v.getUint32(p+20,true);
  const name=new TextDecoder().decode(bytes.slice(p+46,p+46+length)),start=local+30+v.getUint16(local+26,true)+v.getUint16(local+28,true),data=bytes.slice(start,start+size);
  parts.set(name,method===8?new Uint8Array(inflateRawSync(data)):data);p+=46+length+extra+comment;
 }
 return parts;
}
test('shared picture recipes bind every planned case exactly once and retain literal physical evidence',async()=>{
 const r=await load(),manifest=await Bun.file('manifest.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);
 expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:6,cases:12});expect(compiled).toHaveLength(12);expect(r.cases).toHaveLength(12);
 expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(12);
 expect(new Set(r.cases.map((c:any)=>c.scenarioId)).size).toBe(6);
 const generated=registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]});
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(generated.ledger.workflows);
 const fixture=manifest.files.find((f:any)=>f.id===r.baseFixtureId);expect(fixture.role).toBe('fixture');
 const bytes=await Bun.file(fixture.path).bytes();expect(bytes.length).toBe(fixture.bytes);expect(new Bun.CryptoHasher('sha256').update(bytes).digest('hex')).toBe(fixture.sha256);
 const parts=payloads(bytes),decoder=new TextDecoder(),encoder=new TextEncoder();
 for(const c of r.cases){
  const selected=compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.caseId+'"')));
  expect(selected).toHaveLength(1);
  const modified=new Map(parts);
  for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');expect(modified.has(op.part)).toBe(true);const old=decoder.decode(modified.get(op.part));expect(old.split(op.before)).toHaveLength(2);modified.set(op.part,encoder.encode(old.replace(op.before,op.after)));}
  if(c.errorCode){expect(c.errorCode).toBe('PPTX_PICTURE_INVALID');expect(c.expected).toBeUndefined();continue;}
  const slide=decoder.decode(modified.get(r.slidePart));
  expect((slide.match(/<p:pic>/g)??[]).length).toBe(c.expected.length);
  for(const row of c.expected){
   expect(slide).toContain('id="'+row.shapeId+'" name="'+row.name+'"');
   // Descriptions are literal source observations, not inspector-generated goldens.
   expect(slide).toContain('descr="'+row.description+'"');
   if(row.embedded){expect(modified.get(row.embedded.partName)?.length).toBe(row.embedded.byteLength);expect(row.embedded.contentType).toBe('image/png');expect(slide).toContain('r:embed="'+row.embedded.relationshipId+'"');}
   if(row.linked){expect(slide).toContain('asset:link="'+row.linked.relationshipId+'"');expect(decoder.decode(modified.get('ppt/slides/_rels/slide1.xml.rels'))).toContain('Target="'+row.linked.target+'" TargetMode="External"');}
   if(row.transform){expect(slide).toContain('<a:off x="'+row.transform.x+'" y="'+row.transform.y+'"/>');expect(slide).toContain('<a:ext cx="'+row.transform.width+'" cy="'+row.transform.height+'"/>');}
   if(row.groups.length)expect(slide).toContain('id="2000" name="Graphics group"');
  }
 }
});
test('picture history removal refuses forged credit, missing rows and changed feature bytes',async()=>{
 const r=await load(),ledger=await Bun.file('ledgers/workflows.json').json(),text=await Bun.file(r.feature).text(),base=beforePictureInspectionLedger(ledger);
 expect(base.features).not.toContain(r.feature);expect(base.workflows).toHaveLength(beforePictureInsertionLedger(ledger).workflows.length-6);expect(beforePictureInspectionLedger(base)).toEqual(base);
 const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforePictureInspectionLedger(forged)).toThrow('Unreviewed picture');
 const missing=structuredClone(ledger);missing.workflows.splice(missing.workflows.findIndex((w:any)=>w.feature===r.feature),1);expect(()=>beforePictureInspectionLedger(missing)).toThrow('Unreviewed picture');
 expect(beforePictureInspectionFeature(r.feature,text)).toBe('');expect(()=>beforePictureInspectionFeature(r.feature,text+'\n')).toThrow('Unreviewed picture');
});
test('registration seals shared recipe data and refuses invalid supporting paths',()=>{
 const m=registerAsset('ledgers/pptx-picture-inspection.json','{"cases":[]}',{files:[]});expect(m.files[0].role).toBe('workflow-recipe');
 for(const path of ['ledgers/../bad.json','ledgers/recipe.ts','ledgers/Bad.json'])expect(()=>registerAsset(path,'{}',{files:[]})).toThrow('path');
});
test('shared insertion recipes retain all eighteen cases, exact payload provenance and planned registration',async()=>{
 const r=await Bun.file('ledgers/pptx-picture-insertion.json').json(),manifest=await Bun.file('manifest.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);
 expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:6,cases:18});expect(compiled).toHaveLength(18);expect(r.cases).toHaveLength(18);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(18);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const fixture=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(fixture.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();
 for(const c of r.cases){
  const match=compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example?.fault?s.text.endsWith('fault '+c.example.fault):c.example?.kind?s.text.endsWith('for '+c.example.kind):s.text.includes('recipe "'+c.caseId+'"')));expect(match).toHaveLength(1);
  const parts=new Map(original);for(const op of c.operations){if(op.kind==='copy-member'){expect(parts.has(op.part)).toBe(false);expect(parts.has(op.from)).toBe(true);parts.set(op.part,parts.get(op.from)!.slice());}else{expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}}
  const source=c.request.payload;expect(source.fixtureId).toBe(r.baseFixtureId);const bytes=original.get(source.part)!;expect(bytes.length).toBe(source.byteLength);expect(new Bun.CryptoHasher('sha256').update(bytes).digest('hex')).toBe(source.sha256);
  expect([...bytes.slice(0,source.contentType==='image/png'?8:2)]).toEqual(source.contentType==='image/png'?[137,80,78,71,13,10,26,10]:[255,216]);if(source.contentType==='image/jpeg')expect([...bytes.slice(-2)]).toEqual([255,217]);
  if(c.errorCode)expect(c.expected).toBeUndefined();else for(const e of c.expected){expect(e.geometry).toEqual(c.request.geometry);expect(parts.has(e.mediaPart)).toBe(false);expect(e.byteLength).toBe(source.byteLength);expect(e.contentType).toBe(source.contentType);}
 }
 const base=beforePictureInsertionLedger(ledger);expect(base.workflows).toHaveLength(beforePictureReplacementLedger(ledger).workflows.length-6);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforePictureInsertionLedger(forged)).toThrow('Unreviewed picture insertion');
});
test('shared replacement recipes bind fourteen cases with isolated media provenance and planned outcomes',async()=>{
 const r=await Bun.file('ledgers/pptx-picture-replacement.json').json(),manifest=await Bun.file('manifest.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);
 expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:5,cases:14});expect(r.cases).toHaveLength(14);expect(compiled).toHaveLength(14);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(14);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const fixture=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(fixture.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();
 for(const c of r.cases){const match=compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example?.fault?s.text.endsWith('fault '+c.example.fault):c.example?.kind?s.text.endsWith('for '+c.example.kind):s.text.includes('recipe "'+c.caseId+'"')));expect(match).toHaveLength(1);
  const parts=new Map(original);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}
  const source=c.request.payload;expect(source.fixtureId).toBe(r.baseFixtureId);const bytes=original.get(source.part)!;expect(bytes.length).toBe(source.byteLength);expect(new Bun.CryptoHasher('sha256').update(bytes).digest('hex')).toBe(source.sha256);
  if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(parts.has(c.expected.mediaPart)).toBe(false);expect(c.expected.shapeId).toBe(c.request.shapeId);expect(c.expected.byteLength).toBe(source.byteLength);expect(c.expected.contentType).toBe(source.contentType);}
 }
 const base=beforePictureReplacementLedger(ledger);expect(base.workflows).toHaveLength(beforePicturePlacementLedger(ledger).workflows.length-5);expect(beforePictureReplacementLedger(base)).toEqual(base);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforePictureReplacementLedger(forged)).toThrow('Unreviewed picture replacement');
});
test('shared placement has sixteen planned cases with independent rational geometry and crop records',async()=>{
 const r=await Bun.file('ledgers/pptx-picture-placement.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:3,cases:16});expect(compiled).toHaveLength(16);expect(r.cases).toHaveLength(16);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);if(c.errorCode){expect(c.expected).toBeUndefined();continue;}
  const b=c.request.box,i=c.request.options.intrinsic,fit=c.request.options.fit,e=c.expected,w=BigInt(b.width),h=BigInt(b.height),iw=BigInt(i.width),ih=BigInt(i.height),g={...b},crop={left:0,top:0,right:0,bottom:0};
  if(fit==='contain'){if(w*ih<=h*iw)g.height=Number(w*ih/iw);else g.width=Number(h*iw/ih);g.x+=Math.floor((b.width-g.width)/2);g.y+=Math.floor((b.height-g.height)/2);}
  if(fit==='cover'){if(w*ih<h*iw){const discarded=h*iw-w*ih,total=h*iw;crop.left=crop.right=Number((discarded*100000n+total)/(2n*total));}else{const discarded=w*ih-h*iw,total=w*ih;crop.top=crop.bottom=Number((discarded*100000n+total)/(2n*total));}}
  expect(e.geometry).toEqual(g);expect(e.crop).toEqual(crop);
 }
 const base=beforePicturePlacementLedger(ledger);expect(base.workflows).toHaveLength(beforePictureCropLedger(ledger).workflows.length-3);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforePicturePlacementLedger(forged)).toThrow('Unreviewed picture placement');
});
test('shared crop binds seventeen literal variants and preserves planned-only credit',async()=>{
 const r=await Bun.file('ledgers/pptx-picture-crop.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:17});expect(compiled).toHaveLength(17);expect(r.cases).toHaveLength(17);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(17);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}
  if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.crop).toEqual(c.request.crop);for(const side of Object.values(c.expected.crop) as number[])expect(side>=0&&side<=99999&&Number.isInteger(side)).toBe(true);expect(c.expected.crop.left+c.expected.crop.right).toBeLessThan(100000);expect(c.expected.crop.top+c.expected.crop.bottom).toBeLessThan(100000);expect(c.expected.changed).toBe(JSON.stringify(c.expected.beforeCrop)===JSON.stringify(c.expected.crop)?0:1);}
 }
 const base=beforePictureCropLedger(ledger);expect(base.workflows).toHaveLength(beforePictureTransformLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforePictureCropLedger(forged)).toThrow('Unreviewed picture crop');
});
test('shared picture orientation binds eighteen literal cases with planned-only credit',async()=>{
 const r=await Bun.file('ledgers/pptx-picture-transform.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:18});expect(compiled).toHaveLength(18);expect(r.cases).toHaveLength(18);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(18);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}
  if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.transform).toEqual({...c.expected.before,...c.request.patch});expect(c.expected.transform.rotation>=0&&c.expected.transform.rotation<21600000).toBe(true);expect(typeof c.expected.transform.flipH).toBe('boolean');expect(typeof c.expected.transform.flipV).toBe('boolean');expect(c.expected.changed).toBe(Object.keys(c.request.patch).some(k=>c.request.patch[k]!==c.expected.before[k])?1:0);}
 }
 const base=beforePictureTransformLedger(ledger);expect(base.workflows).toHaveLength(beforePictureSvgLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforePictureTransformLedger(forged)).toThrow('Unreviewed picture transform');
});
test('shared SVG recipes bind eleven cases and preserve explicit paired asset provenance',async()=>{
 const r=await Bun.file('ledgers/pptx-picture-svg.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:11});expect(compiled).toHaveLength(11);expect(r.cases).toHaveLength(11);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),parts=payloads(await Bun.file(f.path).bytes());
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.endsWith('for '+c.example.kind)))).toHaveLength(1);const fallback=c.request.fallback;expect(fallback.fixtureId).toBe(r.baseFixtureId);const bytes=parts.get(fallback.part)!;expect(bytes.length).toBe(fallback.byteLength);expect(new Bun.CryptoHasher('sha256').update(bytes).digest('hex')).toBe(fallback.sha256);if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.request.svg).toContain('<svg xmlns="http://www.w3.org/2000/svg"');expect(parts.has(c.expected.svgMediaPart)).toBe(false);expect(parts.has(c.expected.mediaPart)).toBe(false);expect(c.expected.relationshipId).not.toBe(c.expected.svgRelationshipId);}}
 const base=beforePictureSvgLedger(ledger);expect(base.workflows).toHaveLength(beforePictureDeleteLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforePictureSvgLedger(forged)).toThrow('Unreviewed picture svg');
});
test('shared deletion binds seventeen planned cases with exact bounded collection receipts',async()=>{
 const r=await Bun.file('ledgers/pptx-picture-delete.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:17});expect(compiled).toHaveLength(17);expect(r.cases).toHaveLength(17);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(17);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){if(op.kind==='add-literal-member'){expect(parts.has(op.part)).toBe(false);parts.set(op.part,encode.encode(op.value));}else{expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}}
  if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.shapeId).toBe(c.request.shapeId);expect(c.expected.partName).toBe(r.slidePart);for(const name of c.expected.removedMedia)expect(parts.has(name)).toBe(true);for(const id of c.expected.removedRelationships)expect(decode.decode(parts.get('ppt/slides/_rels/slide1.xml.rels'))).toContain('Id="'+id+'"');if(!c.request.options.collectMedia){expect(c.expected.removedRelationships).toEqual([]);expect(c.expected.removedMedia).toEqual([]);}}
 }
 const base=beforePictureDeleteLedger(ledger);expect(base.workflows).toHaveLength(beforeShapeGroupLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforePictureDeleteLedger(forged)).toThrow('Unreviewed picture delete');
});
test('shared shape groups bind sixteen literal cases with explicit identity coordinates',async()=>{
 const r=await Bun.file('ledgers/pptx-shape-group.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:16});expect(compiled).toHaveLength(16);expect(r.cases).toHaveLength(16);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(16);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.geometry).toEqual(c.request.geometry);expect(c.expected.childIds).toEqual([1026,2]);expect(c.expected.shapeId).toBe(1034);}}
 const base=beforeShapeGroupLedger(ledger);expect(base.workflows).toHaveLength(beforeGroupTransformLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeShapeGroupLedger(forged)).toThrow('Unreviewed shape group');
});
test('shared group frames bind twenty-one cases with literal independent mapping vectors',async()=>{
 const r=await Bun.file('ledgers/pptx-group-transform.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:3,cases:21});expect(compiled).toHaveLength(21);expect(r.cases).toHaveLength(21);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(21);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('"'+c.example.variant+'"')))).toHaveLength(1);
  if(c.mapping){let point={...c.mapping.point};for(const t of [...c.mapping.transforms].reverse()){const cx=t.x+t.width/2,cy=t.y+t.height/2,dx=(t.x+(point.x-t.childX)*t.width/t.childWidth-cx)*(t.flipH?-1:1),dy=(t.y+(point.y-t.childY)*t.height/t.childHeight-cy)*(t.flipV?-1:1),radius=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)+t.rotation/60000*Math.PI/180;point={x:cx+radius*Math.cos(angle),y:cy+radius*Math.sin(angle)};}for(const key of ['x','y'])expect(Math.abs(point[key]-c.mapping.expected[key])).toBeLessThanOrEqual(r.tolerance.absoluteEMUs+r.tolerance.relative*Math.abs(c.mapping.expected[key]));continue;}
  const parts=new Map(original);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.transform).toEqual({...c.expected.before,...c.request.patch});expect(c.expected.changed).toBe(Object.keys(c.request.patch).some(k=>c.request.patch[k]!==c.expected.before[k])?1:0);}}
 const base=beforeGroupTransformLedger(ledger);expect(base.workflows).toHaveLength(beforeConnectorsLedger(ledger).workflows.length-3);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeGroupTransformLedger(forged)).toThrow('Unreviewed group transform');
});
test('shared connectors bind fifteen literal ID/site/style cases with planned-only credit',async()=>{
 const r=await Bun.file('ledgers/pptx-connectors.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:15});expect(compiled).toHaveLength(15);expect(r.cases).toHaveLength(15);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(15);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}if(c.errorCode)expect(c.expected).toBeUndefined();else{const e=c.expected;expect(e.shapeId).toBe(2002);expect(e.start.shapeId).toBe(c.request.start.shapeId);expect(e.end.shapeId).toBe(c.request.end.shapeId);expect(e.start.site).toBe(c.request.start.site);expect(e.end.site).toBe(c.request.end.site);expect(e.geometry).toEqual({x:Math.min(e.start.x,e.end.x),y:Math.min(e.start.y,e.end.y),width:Math.abs(e.end.x-e.start.x),height:Math.abs(e.end.y-e.start.y),flipH:e.end.x<e.start.x,flipV:e.end.y<e.start.y});}}
 const base=beforeConnectorsLedger(ledger);expect(base.workflows).toHaveLength(beforeDiagramsLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeConnectorsLedger(forged)).toThrow('Unreviewed connectors');
});
test('shared diagrams bind fourteen deterministic graph cases with planned-only credit',async()=>{
 const r=await Bun.file('ledgers/pptx-diagrams.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:14});expect(compiled).toHaveLength(14);expect(r.cases).toHaveLength(14);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(14);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder();
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');expect(decode.decode(original.get(op.part)).split(op.before)).toHaveLength(2);}if(c.errorCode)expect(c.expected).toBeUndefined();else{const o=c.request.options;expect(c.expected.nodes).toEqual(c.request.nodes.map((n:any,i:number)=>({key:n.key,shapeId:1034+i,geometry:{x:o.x+(o.direction==='row'?i*(o.nodeWidth+o.gap):0),y:o.y+(o.direction==='column'?i*(o.nodeHeight+o.gap):0),width:o.nodeWidth,height:o.nodeHeight}})));for(const e of c.expected.edges){expect(e.start.shapeId).toBe(c.expected.nodes.find((n:any)=>n.key===e.from).shapeId);expect(e.end.shapeId).toBe(c.expected.nodes.find((n:any)=>n.key===e.to).shapeId);expect(e.start.site).toBe(o.direction==='row'?3:2);expect(e.end.site).toBe(o.direction==='row'?1:0);}}}
 const base=beforeDiagramsLedger(ledger);expect(base.workflows).toHaveLength(beforeSmartArtInspectionLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeDiagramsLedger(forged)).toThrow('Unreviewed diagrams');
});
test('shared SmartArt inspection binds twelve explicit graph recipes without physical fixture credit',async()=>{
 const r=await Bun.file('ledgers/pptx-smartart-inspection.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.physicalSmartArtFixtureAvailable).toBe(false);expect(r.counts).toEqual({ids:2,cases:12});expect(compiled).toHaveLength(12);expect(r.cases).toHaveLength(12);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(12);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){if(op.kind==='add-literal-member'){expect(parts.has(op.part)).toBe(false);parts.set(op.part,encode.encode(op.value));}else{expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}}if(c.errorCode)expect(c.expected).toBeUndefined();else for(const row of c.expected){expect(row.roots.map((a:any)=>a.role)).toEqual(['data','layout','style','colors']);for(const a of row.parts)expect(parts.get(a.partName)?.length).toBe(a.byteLength);expect(Object.values(row.limits).filter(v=>typeof v==='boolean')).toEqual([false,false,false,false]);}}
 const base=beforeSmartArtInspectionLedger(ledger);expect(base.workflows).toHaveLength(beforeSmartArtCopyLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeSmartArtInspectionLedger(forged)).toThrow('Unreviewed smartart-inspection');
});
test('shared SmartArt copy binds eight explicit closure/remap cases without Office fixture credit',async()=>{
 const r=await Bun.file('ledgers/pptx-smartart-copy.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.physicalSmartArtFixtureAvailable).toBe(false);expect(r.counts).toEqual({ids:2,cases:8});expect(compiled).toHaveLength(8);expect(r.cases).toHaveLength(8);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(8);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();
 for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){if(op.kind==='add-literal-member'){expect(parts.has(op.part)).toBe(false);parts.set(op.part,encode.encode(op.value));}else{expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}}if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.shapeId).toBe(c.request.sameSlide?2001:r.destinationRecipe.initialMaximumShapeId+1);expect(c.expected.nodeIdentityCount).toBe(1);expect(c.expected.drawingIdentityCount).toBe(1);expect(decode.decode(parts.get('ppt/diagrams/data1.xml'))).toContain('presAssocID="{11111111-1111-1111-1111-111111111111}"');expect(decode.decode(parts.get('ppt/diagrams/drawing1.xml'))).toContain('id="5" name="Drawing node"');}}
 const base=beforeSmartArtCopyLedger(ledger);expect(base.workflows).toHaveLength(beforeAutoShapesLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeSmartArtCopyLedger(forged)).toThrow('Unreviewed smartart-copy');
});
test('shared AutoShapes bind eighteen cases and exact bounded preset adjustment policy',async()=>{
 const r=await Bun.file('ledgers/pptx-autoshapes.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:18});expect(compiled).toHaveLength(18);expect(r.cases).toHaveLength(18);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(18);expect(Object.keys(r.presets)).toEqual(['rect','ellipse','triangle','diamond','roundRect']);expect(r.presets.roundRect.adjustments.adj).toEqual({min:0,max:50000,default:16667});
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder();for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');expect(decode.decode(original.get(op.part)).split(op.before)).toHaveLength(2);}if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.geometry).toEqual(c.request.geometry);expect(c.expected.preset).toBe(c.request.preset);expect(c.expected.adjustments).toEqual(c.request.preset==='roundRect'?{adj:c.request.options.adjustments?.adj??16667}:{});}}
 const base=beforeAutoShapesLedger(ledger);expect(base.workflows).toHaveLength(beforeFreeformLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeAutoShapesLedger(forged)).toThrow('Unreviewed autoshapes');
});
test('shared freeform binds fifteen exact move/line/close cases with planned-only credit',async()=>{
 const r=await Bun.file('ledgers/pptx-freeform.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:15});expect(compiled).toHaveLength(15);expect(r.cases).toHaveLength(15);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(15);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder();for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');expect(decode.decode(original.get(op.part)).split(op.before)).toHaveLength(2);}if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.geometry).toEqual(c.request.geometry);expect(c.expected.path).toEqual(c.request.path);for(const command of c.expected.path.commands){expect(['move','line','close']).toContain(command.op);if(command.op!=='close'){expect(Number.isInteger(command.x)&&command.x>=0&&command.x<=c.expected.path.width).toBe(true);expect(Number.isInteger(command.y)&&command.y>=0&&command.y<=c.expected.path.height).toBe(true);}}}}
 const base=beforeFreeformLedger(ledger);expect(base.workflows).toHaveLength(beforeZOrderLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeFreeformLedger(forged)).toThrow('Unreviewed freeform');
});
test('shared z-order binds fifteen exact selected sibling permutations with planned-only credit',async()=>{
 const r=await Bun.file('ledgers/pptx-z-order.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:15});expect(compiled).toHaveLength(15);expect(r.cases).toHaveLength(15);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(15);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}if(c.errorCode)expect(c.expected).toBeUndefined();else{const order=[...c.expected.before],slots=order.map((id:number,index:number)=>c.request.order.includes(id)?index:-1).filter((i:number)=>i>=0);slots.forEach((slot:number,i:number)=>order[slot]=c.request.order[i]);expect(order).toEqual(c.expected.order);expect(c.expected.changed).toBe(JSON.stringify(order)===JSON.stringify(c.expected.before)?0:1);}}
 const base=beforeZOrderLedger(ledger);expect(base.workflows).toHaveLength(beforeGradientsLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeZOrderLedger(forged)).toThrow('Unreviewed z-order');
});
test('shared gradients bind eighteen exact stop/colour-reference cases with planned-only credit',async()=>{
 const r=await Bun.file('ledgers/pptx-gradients.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:18});expect(compiled).toHaveLength(18);expect(r.cases).toHaveLength(18);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(18);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.gradient).toEqual(c.request.gradient);expect(c.expected.gradient.stops[0].position).toBe(0);expect(c.expected.gradient.stops.at(-1).position).toBe(100000);expect(c.expected.changed).toBe(JSON.stringify(c.expected.before)===JSON.stringify(c.expected.gradient)?0:1);expect(decode.decode(parts.get(r.slidePart))).toContain('<a:fillRef idx="2"><a:schemeClr val="accent3"/></a:fillRef>');}}
 const base=beforeGradientsLedger(ledger);expect(base.workflows).toHaveLength(beforeOpacityLedger(ledger).workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeGradientsLedger(forged)).toThrow('Unreviewed gradients');
});
test('shared opacity binds twenty-four distinct alpha profiles with planned-only credit',async()=>{
 const r=await Bun.file('ledgers/pptx-opacity.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:3,cases:24});expect(compiled).toHaveLength(24);expect(r.cases).toHaveLength(24);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(24);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.value).toBe(c.request.value);expect(c.expected.value>=0&&c.expected.value<=100000&&Number.isInteger(c.expected.value)).toBe(true);expect(c.expected.changed).toBe(c.expected.before===c.expected.value?0:1);}}
 const base=beforeOpacityLedger(ledger);expect(base.workflows).toHaveLength(beforeOutlinesLedger(ledger).workflows.length-3);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeOpacityLedger(forged)).toThrow('Unreviewed opacity');
});
test('shared outlines bind twenty-one exact decoration cases with planned-only credit',async()=>{
 const r=await Bun.file('ledgers/pptx-outlines.json').json(),ledger=await Bun.file('ledgers/workflows.json').json(),manifest=await Bun.file('manifest.json').json(),text=await Bun.file(r.feature).text(),compiled=cases(r.feature,text);expect(r.executionCredit).toBe(false);expect(r.counts).toEqual({ids:2,cases:21});expect(compiled).toHaveLength(21);expect(r.cases).toHaveLength(21);expect(new Set(r.cases.map((c:any)=>c.caseId)).size).toBe(21);
 expect(ledger.workflows.filter((w:any)=>w.feature===r.feature)).toEqual(registerWorkflow(r.feature,text,{files:[]},{features:[],workflows:[]}).ledger.workflows);
 const f=manifest.files.find((f:any)=>f.id===r.baseFixtureId),original=payloads(await Bun.file(f.path).bytes()),decode=new TextDecoder(),encode=new TextEncoder();for(const c of r.cases){expect(compiled.filter((p:any)=>p.scenarioId===c.scenarioId&&p.steps.some((s:any)=>c.example.fault?s.text.endsWith('fault '+c.example.fault):s.text.includes('recipe "'+c.example.variant+'"')))).toHaveLength(1);const parts=new Map(original);for(const op of c.operations){expect(op.kind).toBe('replace-literal-once');const s=decode.decode(parts.get(op.part));expect(s.split(op.before)).toHaveLength(2);parts.set(op.part,encode.encode(s.replace(op.before,op.after)));}if(c.errorCode)expect(c.expected).toBeUndefined();else{expect(c.expected.outline).toEqual({...c.expected.before,...c.request.patch});expect(c.expected.changed).toBe(Object.keys(c.request.patch).some(k=>JSON.stringify(c.request.patch[k])!==JSON.stringify(c.expected.before[k]))?1:0);expect(decode.decode(parts.get(r.slidePart))).toContain('val="accent2"');}}
 const base=beforeOutlinesLedger(ledger);expect(base.workflows).toHaveLength(ledger.workflows.length-2);const forged=structuredClone(ledger);forged.workflows.find((w:any)=>w.feature===r.feature).consumers.bun.status='implemented';expect(()=>beforeOutlinesLedger(forged)).toThrow('Unreviewed outlines');
});
