import {test,expect} from 'bun:test';
import {execFileSync} from 'node:child_process';
import {cases} from '../scripts/verify.ts';
import {inspectFixtureArchive} from '../scripts/fixture-content.ts';
import {beforeRetainedStyleWordFeature,beforePptxFormattingFeature,beforePptxFormattingLedger} from './xml-generalization-helpers.ts';
const sha=(v:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(v).digest('hex');
const load=()=>Bun.file('ledgers/pptx-formatting.json').json();
test('twenty additional PPTX cases seal explicit property values with honest source provenance and no consumer credit',async()=>{
 const l=await load(),m=await Bun.file('manifest.json').json(),registry=await Bun.file('ledgers/workflows.json').json(),all=[];
 expect(l.sourceRevision).toBe('5dc02ae970e2eaf5ed3e261324ae3961e08bb1c9');expect(l.baselineCounts).toEqual({features:64,scenarios:324,cases:811,assets:351});expect(l.executionCredit).toBe(false);expect(l.retiredScenarioIds).toEqual([]);expect(l.records).toHaveLength(20);expect(l.files).toHaveLength(4);expect(l.records.filter((r:any)=>r.sourceId)).toHaveLength(3);expect(l.records.filter((r:any)=>r.provenanceKind==='new-project-authored-production-contract')).toHaveLength(17);
 for(const f of l.files){const text=beforeRetainedStyleWordFeature(f.path,await Bun.file(f.path).text());expect(sha(text)).toBe(f.afterSha256);expect(beforePptxFormattingFeature(f.path,text)).toBe(f.beforeText);if(f.beforeText)expect(execFileSync('git',['show',`${l.sourceRevision}:${f.path}`]).toString()).toBe(f.beforeText);const rows=cases(f.path,text).filter(c=>l.records.some((r:any)=>r.id===c.scenarioId));expect(rows).toEqual(f.scenarios.flatMap((s:any)=>s.after));all.push(...rows);}
 expect(all).toHaveLength(20);expect(new Set(all.map(c=>c.scenarioId)).size).toBe(20);expect(all.reduce((n,c)=>n+c.steps.length,0)).toBe(182);
 for(const r of l.records){expect(r.id).toBe('@id-pptx-formatting-'+r.kind);expect(r.fixtureId).toBe(l.fixture.id);expect(r.executionCredit).toBe(false);const row=registry.workflows.find((w:any)=>w.id===r.id);expect(row.expandedCases).toBe(1);expect(row.consumers).toEqual({bun:{status:'planned',evidence:[]},go:{status:'planned',evidence:[]},python:{status:'planned',evidence:[]}});if(r.sourceId){const text=await Bun.file(r.sourceFeature).text();expect(sha(text)).toBe(r.sourceSha256);expect(text).toContain(r.sourceBlock);expect(sha(r.sourceBlock)).toBe(r.sourceBlockSha256);}else expect(r.sourceBlock).toBeUndefined();}
 expect(beforePptxFormattingLedger(registry)).toEqual(JSON.parse(execFileSync('git',['show',`${l.sourceRevision}:ledgers/workflows.json`]).toString()));expect(m.files.find((f:any)=>f.id===l.fixture.id).scenarioIds).toEqual(l.records.map((r:any)=>r.id));
});
test('derived formatting input preserves all nineteen other payloads and explicitly seals the sole Body recipe',async()=>{
 const l=await load(),f=l.fixture,bytes=await Bun.file(f.path).bytes(),old=await Bun.file(f.derivedFrom.path).bytes();expect(bytes.length).toBe(8634);expect(sha(bytes)).toBe('84e7a8a3681d0e43d4c8a29c37e68386721dfb5df13a36b8bd17a3ebc1fb1fb2');expect(sha(old)).toBe(f.derivedFrom.sha256);const a=inspectFixtureArchive(old),b=inspectFixtureArchive(bytes);expect(b.members).toHaveLength(20);expect(b.members.map(({name,sha256})=>({name,sha256}))).toEqual(f.members);
 const changed=b.members.filter(n=>a.members.find(m=>m.name===n.name)?.sha256!==n.sha256).map(m=>m.name);expect(changed).toEqual(['ppt/slides/slide2.xml']);const read=(path:string)=>execFileSync('unzip',['-p',path,'ppt/slides/slide2.xml']).toString();expect(read(f.path)).toBe(read(f.derivedFrom.path).replace(f.derivedFrom.beforeParagraph,f.derivedFrom.afterParagraph));expect(l.specification.edition).toBe('ECMA-376-1:2016');expect(l.specification.clauses).toContain('21.1.2.3.9');
});
test('historical formatting reconstruction fails on predicate or credit drift',async()=>{const l=await load(),f=l.files[0],text=await Bun.file(f.path).text();expect(()=>beforePptxFormattingFeature(f.path,text.replace('invalid-visibility','false-success'))).toThrow('Unreviewed PPTX formatting');const r=await Bun.file('ledgers/workflows.json').json();r.workflows.find((r:any)=>r.id===l.records[0].id).consumers.bun.status='implemented';expect(()=>beforePptxFormattingLedger(r)).toThrow('Unreviewed PPTX formatting');});
